apiVersion: v1
kind: Service
metadata:
  name: {{ include "acme-dns.fullname" . }}-dns
  labels:
    {{- include "acme-dns.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.dns.type }}
  {{- if .Values.service.dns.ipDualStack.enabled }}
  ipFamilies: {{ toYaml .Values.service.dns.ipDualStack.ipFamilies | nindent 4 }}
  ipFamilyPolicy: {{ .Values.service.dns.ipDualStack.ipFamilyPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.service.dns.port }}
      targetPort: tcpdns
      protocol: TCP
      name: tcp
    - port: {{ .Values.service.dns.port }}
      targetPort: udpdns
      protocol: UDP
      name: udp
  selector:
    {{- include "acme-dns.selectorLabels" . | nindent 6 }}
